# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/agentic',
                'doc_host': 'https://lubok-dot.github.io',
                'git_url': 'https://github.com/lubok-dot/agentic',
                'lib_path': 'agentic'},
  'syms': {'agentic.core': {'agentic.core.foo': ('core.html#foo', 'agentic/core.py')}}}
