name: CI
on: [workflow_dispatch, pull_request, push]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}  # Use secret in the environment
      TAVILY_API_KEY: ${{ secrets.TAVILY_API_KEY }}
      RIZA_API_KEY: ${{ secrets.RIZA_API_KEY }}
    steps:
      - name: Check out repository (clean clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.6'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Ensure all required dependencies are installed
          pip install -e '.[dev]'  # Install development dependencies

      - name: Verify dependency installation
        run: |
          python -c "import nbdev; print('nbdev installed')"
          python -c "import langgraph; print('langgraph installed')"
          python -c "import datasets; print('datasets installed')"

      - name: Run nbdev commands
        run: |
          nbdev_install_hooks
          nbdev_export
          nbdev_test